#!/bin/bash

#SBATCH --partition=cbuild
#SBATCH --gpus=0
#SBATCH --job-name=InstallEnvironment
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=00:30:00
#SBATCH --output=./jobs/output/install_environment_%A.out


module purge
module load 2023
module load Anaconda3/2023.07-2

cd $HOME/thesis/elk-generalization/

conda create --name elk-generalization python=3.11
source activate elk-generalization
pip3 install torch torchvision torchaudio
pip3 install -r requirements.txt